INSERT INTO [DBO].FaixaEtaria(DESCRICAO) VALUES('Até 30 anos')
INSERT INTO [DBO].FaixaEtaria(DESCRICAO) VALUES('De 30 a 50 anos')
INSERT INTO [DBO].FaixaEtaria(DESCRICAO) VALUES('De 50 a 65 anos')
INSERT INTO [DBO].FaixaEtaria(DESCRICAO) VALUES('Acima de 65 anos')

INSERT INTO [DBO].Convenio(DESCRICAO) VALUES('INSS')
INSERT INTO [DBO].Convenio(DESCRICAO) VALUES('SIAPE')
INSERT INTO [DBO].Convenio(DESCRICAO) VALUES('Forças Armadas')
INSERT INTO [DBO].Convenio(DESCRICAO) VALUES('Outros')

INSERT INTO [DBO].FaixaSalarial(DESCRICAO) VALUES('Até 2 SM')
INSERT INTO [DBO].FaixaSalarial(DESCRICAO) VALUES('De 2 a 4 SM')
INSERT INTO [DBO].FaixaSalarial(DESCRICAO) VALUES('De 4 a 6 SM')
INSERT INTO [DBO].FaixaSalarial(DESCRICAO) VALUES('Acima de 6 SM')

INSERT INTO [DBO].MotivoEmprestimo(DESCRICAO) VALUES('Pagar contas')
INSERT INTO [DBO].MotivoEmprestimo(DESCRICAO) VALUES('Reforma da Casa')
INSERT INTO [DBO].MotivoEmprestimo(DESCRICAO) VALUES('Compra de Carro')
INSERT INTO [DBO].MotivoEmprestimo(DESCRICAO) VALUES('Outras')